# Request
int8[] target_positions
int8[] target_speeds
int8[] pressure_limits
int8 pid_kp
int8 pid_ki
int8 pid_kd
string hand_selection  # "right", "left", "both" (default="right")
---
# Response
bool success
string message
